version: '3.8'

services:
  jenkins-blueocean:
    image: jenkinsci/blueocean:latest
    container_name: jenkins-blueocean
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home

  docker:
    image: docker:dind
    container_name: docker
    privileged: true
    ports:
      - "2375:2375"
      - "2376:2376"

volumes:
  jenkins_home:
