
name: Final-T10-Workflow

on: [push]

jobs:
  build-and-test:
    
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout Repository
        uses: actions/checkout@v4

 
      - name: Print Welcome Message
        run: |
          echo "Starting the final task execution..."
          echo "Current working directory: $(pwd)"
          echo "Workflow executed successfully by Sara Dobrevska."